name: hikeguide
description: "Enjoy hiking with a clean mind"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  rive: ^0.13.20
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  cloud_firestore: ^5.6.6
  bottom_bar_matu: ^1.5.0
  cloud_functions: ^5.4.0
  provider: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/ 
