name: hikehype
description: "Enjoy hiking with a clean mind"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  rive: ^0.13.20
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/ 
