// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrHJ3RioKHfQLnN0PZsa07PF_Vp-lRFk0',
    appId: '1:275326735244:android:cec825e5748d96cd033ca9',
    messagingSenderId: '275326735244',
    projectId: 'e4route',
    storageBucket: 'e4route.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0u28B4YpPxxuvSpj_avHemYzNNibh15A',
    appId: '1:275326735244:ios:9d9f2cf260136879033ca9',
    messagingSenderId: '275326735244',
    projectId: 'e4route',
    storageBucket: 'e4route.firebasestorage.app',
    androidClientId: '275326735244-0jt5fk8180no539nn96h303i6nsfj3su.apps.googleusercontent.com',
    iosClientId: '275326735244-t5cu2dnr5d3j4lfesu06eriv6osms9oq.apps.googleusercontent.com',
    iosBundleId: 'com.winconsulting.hikeguide',
  );
}
